# Generated by Django 5.1.5 on 2025-01-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Student',
        ),
    ]
